export const mockData = [
  {
    negative: false,
    symbol: '%',
    value: 0.45,
    previous: 0.47,
    name: 'Overall Bounce rate',
  },
  {
    negative: true,
    symbol: '%',
    value: 0.45,
    previous: 0.47,
    name: 'E-Conversion rate',
    chart: [
      {
        label: 'E-CVR',
        fill: true,
        lineTension: 0.1,
        backgroundColor: 'rgba(75,192,192,0.4)',
        borderColor: '#55D432',
        borderCapStyle: 'butt',
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 'rgba(75,192,192,1)',
        pointBackgroundColor: '#fff',
        pointBorderWidth: 1,
        pointHoverRadius: 5,
        pointHoverBackgroundColor: 'rgba(75,192,192,1)',
        pointHoverBorderColor: 'rgba(220,220,220,1)',
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [65, 59, 80, 81, 56, 55, 40],
      },
    ],
  },
  {
    negative: true,
    symbol: '%',
    value: 0.8,
    previous: 0.67,
    name: 'Overall Bounce rate',
  },
  {
    negative: true,
    symbol: 'Users',
    value: 1431221,
    previous: 131221,
    name: 'Users',
  },
  {
    negative: true,
    symbol: '%',
    value: 0.8,
    previous: 0.67,
    name: 'Overall Bounce rate',
  },
  {
    negative: true,
    symbol: 'Users',
    value: 1431221,
    previous: 131221,
    name: 'Users',
  },
];
